spring:
  application:
    name: zuul-gateway
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.10.100:9411/
    enabled: true
    sender:
      type: RABBIT
  rabbitmq:
    addresses: 192.168.10.100
    port: 15672
    username: admin
    password: 12345
    virtual-host: sleuth

server:
  port: 9310

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

zuul:
  prefix: /v1
  routes:
    # http://localhost:9310/v1/user/
    # user Api
    user-api:
      path: /user/**
      serviceId: user-service
    # order Api
    order-api:
      path: /order/**
      serviceId: order-service

logging:
  config: classpath:logback-spring.xml
  level: debug
