spring:
  application:
    name: user-service
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.10.100:9411/
    enabled: true
    sender:
      type: RABBIT
  rabbitmq:
    addresses: 192.168.10.100
    port: 15672
    username: admin
    password: 12345
    virtual-host: sleuth

server:
  port: 9100

eureka:
  client:
    #在此指定服务注册中心地址
    service-url:
      defaultZone: http://localhost:8080/eureka/
      # 开启健康检查（需要spring-boot-starter-actuator依赖）
      healthcheck:
        enabled: true
  instance:
    #续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 30
    #续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10

logging:
  config: classpath:logback-spring.xml


