spring:
  application:
    name: hystrix-turbine
  rabbitmq:
    addresses: 192.168.10.100
    port: 5672
    username: admin
    password: 12345

server:
  port: 9240

management:
  server:
    port: 9250

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

turbine:
  # 参数指定了需要收集监控信息的服务名；
  app-config: eureka-feign-hystrix
  # 参数指定了集群名称为default，当我们服务数量非常多的时候，可以启动多个Turbine服务来构建不同的聚合集群
  cluster-name-expression: new String("default")
   #参数设置为true，可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以host来区分不同的服务，
   #这会使得在本地调试的时候，本机上的不同服务聚合成一个服务来统计。
  combine-host-port: true



